### ISSUE TITLE
Undefined reference to symbol 'XCreateWindow'

### ISSUE THREAD

**Issue by forresthopkinsa** [slowmoVideo/slowmoVideo#42]
When trying to make, I get this error:

```
/usr/bin/ld: CMakeFiles/slowmoFlowBuilder.dir/flowBuilder.cpp.o: undefined reference to symbol 'XCreateWindow'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [V3D/Apps/GL/slowmoFlowBuilder] Error 1
make[1]: *** [V3D/Apps/GL/CMakeFiles/slowmoFlowBuilder.dir/all] Error 2
make: *** [all] Error 2
```

I'm running Ubuntu 14.04. I used cmake with the following flags in order to prevent the other errors I was getting before:
`cmake -DUSE_QTKIT=FALSE -DENABLE_TESTS=FALSE ../src`

I've been debugging this for days, and I keep making progress, but this most recent error has been a real stumbling block.

**Comment by valgit** [comment]
Did you installed X11 developpment libraries ?
can you paste log of make in "verbose mode" ?

**Comment by lherbolt** [comment]
Hi,
I have same issue on latest fedora 22.
I tried attach make -d output with no luck. I'll try it again. Let me know what else you need.

 
```
Reaping winning child 0xf00730 PID 23480 
Live child 0xf00730 (V3D/Apps/GL/slowmoFlowBuilder) PID 23481 
/usr/bin/ld: CMakeFiles/slowmoFlowBuilder.dir/flowBuilder.cpp.o: undefined reference to symbol 'XCreateWindow'
/usr/lib64/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Reaping losing child 0xf00730 PID 23481 
V3D/Apps/GL/CMakeFiles/slowmoFlowBuilder.dir/build.make:154: recipe for target 'V3D/Apps/GL/slowmoFlowBuilder' failed
make[2]: *** [V3D/Apps/GL/slowmoFlowBuilder] Error 1
Removing child 0xf00730 PID 23481 from chain.
Reaping losing child 0xf0a0a0 PID 23464 
CMakeFiles/Makefile2:848: recipe for target 'V3D/Apps/GL/CMakeFiles/slowmoFlowBuilder.dir/all' failed
make[1]: *** [V3D/Apps/GL/CMakeFiles/slowmoFlowBuilder.dir/all] Error 2
Removing child 0xf0a0a0 PID 23464 from chain.
Reaping losing child 0x14fcf30 PID 22601 
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
Removing child 0x14fcf30 PID 22601 from chain.

```

```
ll /usr/lib64/libX11.so.6
lrwxrwxrwx. 1 root root 15 Mar 10  2015 /usr/lib64/libX11.so.6 -> libX11.so.6.3.0
```

**Comment by lherbolt** [comment]
$ readelf -s /usr/lib64/libX11.so.6 | grep XCreateWindow
   555: 00000000000410d0   265 FUNC    GLOBAL DEFAULT   11 XCreateWindow

**Comment by lherbolt** [comment]
One more update:
from Xlib.h for me it look like bug in Makefile created by cmake, but I don't know how cmake works. :-(

```
extern Window XCreateWindow(
    Display*            /* display */,
    Window              /* parent */,
    int                 /* x */,
    int                 /* y */,
    unsigned int        /* width */,
    unsigned int        /* height */,
    unsigned int        /* border_width */,
    int                 /* depth */,
    unsigned int        /* class */,
    Visual*             /* visual */,
    unsigned long       /* valuemask */,
    XSetWindowAttributes*       /* attributes */
);
```

**Comment by valgit** [comment]
Can you try to disable the build of slowmoFlowBuilder as it's a lot's out of date in recent ubuntu and maybe does not compile correctly ?

**Comment by lherbolt** [comment]
How? As I wrote newbie in cmake

**Comment by valgit** [comment]
can you use `make VERBOSE=1` and post the result log ?

**Comment by pmo-19** [comment]
I stumbled minutes ago on the same error in Ubuntu Trusty 14.04.

`Linking CXX executable slowmoFlowBuilder
cd /home/ubuntu-trusty/jean/Downloads/slowmovideo/slowmovideo-0.4+git20150930/obj-x86_64-linux-gnu/V3D/Apps/GL && /usr/bin/cmake -E cmake_link_script CMakeFiles/slowmoFlowBuilder.dir/link.txt --verbose=1`

`/usr/bin/c++   -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -O3 -D_FORTIFY_SOURCE=2  -Wall -g   -Wl,-Bsymbolic-functions -Wl,-z,relro CMakeFiles/slowmoFlowBuilder.dir/flowBuilder.cpp.o CMakeFiles/slowmoFlowBuilder.dir/__/__/__/slowmoVideo/lib/flowField_sV.cpp.o CMakeFiles/slowmoFlowBuilder.dir/__/__/__/slowmoVideo/lib/flowRW_sV.cpp.o  -o slowmoFlowBuilder  -L/home/ubuntu-trusty/jean/Downloads/slowmovideo/slowmovideo-0.4+git20150930/src/V3D -rdynamic ../../../libV3D.a -ljpeg -lpng -lz -lGLU -lGL -lGLEW -lglut -Wl,-rpath,/home/ubuntu-trusty/jean/Downloads/slowmovideo/slowmovideo-0.4+git20150930/src/V3D: 
/usr/bin/ld: CMakeFiles/slowmoFlowBuilder.dir/flowBuilder.cpp.o: undefined reference to symbol 'XCreateWindow'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[4]: *** [V3D/Apps/GL/slowmoFlowBuilder] Error 1
make[4]: Leaving directory ``/home/ubuntu-trusty/jean/Downloads/slowmovideo/slowmovideo-0.4+git20150930/obj-x86_64-linux-gnu'
make[3]: *** [V3D/Apps/GL/CMakeFiles/slowmoFlowBuilder.dir/all] Error 2
make[3]: /usr/bin/cmake -E cmake_progress_report /home/ubuntu-trusty/jean/Downloads/slowmovideo/slowmovideo-0.4+git20150930/obj-x86_64-linux-gnu/CMakeFiles 
*** Waiting for unfinished jobs....
`

I focused on the message `error adding symbols: DSO missing from command line

I found at least 2 websites pointing to missing flags at compile time.

http://stackoverflow.com/questions/31165822/webrtc2sip-error-adding-symbols-dso-missing-from-command-line

http://askubuntu.com/questions/521706/error-adding-symbols-dso-missing-from-command-line-while-compiling-g13-driver

The answer from stackoverflow looks more elaborate. I will try that tomorrow. Otherwise the libraries and source file are OK. in Debian libX11.so.6 is part of package libx11-6 and the header file X11/Xlib.h is part of libx11-dev. Both are properly installed otherwise it won't compile. We have a problem at link time, meaning some compilation options are missing.

What you all thing about that ?

Well as I was about to close I found this link which is closer to our problem and bolster my own impression.

https://github.com/tum-vision/lsd_slam/issues/29

http://stackoverflow.com/questions/23585435/cannot-call-xinitthreads

`"undefined reference to symbol"` is a linker error, not a compiler error. If you get this message, the compiler has already finished compiled the file into an object file, but is unable to find the shared library which contains the function to link the object file into an executable.

Using gcc, it generally means you have to add some -l flags, like so:

`gcc prog.c -lX11`

`You can try adding it in the CMakesList.txt that references live_slam:
https://github.com/tum-vision/lsd_slam/blob/master/lsd_slam_core/CMakeLists.txt`

One participant acknowledges that adding the X11 library to the compilation command line as `-lX11` solves the issue.

**Comment by valgit** [comment]
I agree with you about this error is an linker error. but from what I see in your logs, there is no -lX11 in your link command contrary to mine in my ubuntu ! What I didn't understand is why  as I have never specify -lX11 as a "forced dependecies". I will check what packages I have ASAP

**Comment by pmo-19** [comment]
Good morning. I believe you shouldn’t see an -lX11 on the "Linking CXX executable slowmoFlowBuilder" which where the error pops up and the part of my log I did publish above, at least if the source flowBuilder.cpp was not build against the X11 library.

However to correct this error I would expect to see a -lX11 on the compile command line for the flowBuilder.cpp source. For this to happen I think X11 should appear at least once in src/CMakeLists.txt and that's not yet the case ?

The project I mentioned in my previous post had to add X11 in  CMakeLists.txt in these lines:

`# build shared library.
rosbuild_add_library(lsdslam SHARED ${SOURCE_FILES})
target_link_libraries(lsdslam ${FABMAP_LIB} g2o_core g2o_stuff csparse cxsparse g2o_solver_csparse g2o_csparse_extension g2o_types_sim3 g2o_types_sba X11)
rosbuild_link_boost(lsdslam thread)
`

Here is the compile command line for flowBuilder.cpp source file in my attempted build:

`Building CXX object V3D/Apps/GL/CMakeFiles/slowmoFlowBuilder.dir/flowBuilder.cpp.o
cd /home/ubuntu-trusty/jean/Downloads/slowmovideo/slowmovideo-0.4+git20150930/obj-x86_64-linux-gnu/V3D/Apps/GL && /usr/bin/c++   -DDISABLE_REDEFINITIONS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_SCRIPT_LIB -DQT_XML_LIB -DV3DLIB_ENABLE_GPGPU -DV3DLIB_ENABLE_LIBJPEG -DV3DLIB_ENABLE_LIBPNG -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -O3 -D_FORTIFY_SOURCE=2  -Wall -g -isystem /usr/include/qt4 -isystem /usr/include/qt4/QtScript -isystem /usr/include/qt4/QtGui -isystem /usr/include/qt4/QtXml -isystem /usr/include/qt4/QtCore -I/usr/include/opencv -I/home/ubuntu-trusty/jean/Downloads/slowmovideo/slowmovideo-0.4+git20150930/obj-x86_64-linux-gnu -I/home/ubuntu-trusty/jean/Downloads/slowmovideo/slowmovideo-0.4+git20150930/src/slowmoVideo/tr -I/usr/include/GL -I/home/ubuntu-trusty/jean/Downloads/slowmovideo/slowmovideo-0.4+git20150930/src/V3D/. -I/home/ubuntu-trusty/jean/Downloads/slowmovideo/slowmovideo-0.4+git20150930/src/V3D/Config -I/home/ubuntu-trusty/jean/Downloads/slowmovideo/slowmovideo-0.4+git20150930/src/slowmoVideo/lib    -o CMakeFiles/slowmoFlowBuilder.dir/flowBuilder.cpp.o -c /home/ubuntu-trusty/jean/Downloads/slowmovideo/slowmovideo-0.4+git20150930/src/V3D/Apps/GL/flowBuilder.cpp
`
To get flowBuilder.cpp.o properly build we would need to have -I/usr/include/X11 and that's not the case.

As I said earlier X11 is never mentioned in your src/CMakeLists.txt file and my belief is it should appear there.

I am not an expert in CMake so I don't know exactly were to add the X11 library. Do you have some hints about where I have to add X11 within src/CMakeLists.txt file ?

**Comment by pmo-19** [comment]
Well. I have found the solution and will propose a pull request.

**Comment by forresthopkinsa** [comment]
As a side note, I'm running this through Crouton on a Chromebook.

I'm just trying to figure out why this would be working for some systems, and not for others. Clearly the lack of an X11 reference in Cmake wasn't a problem with most people's systems.

@lherbolt and @pmo-19 are either of you using Chromebooks? I really want to figure out what made this run differently in the first place.

**Comment by valgit** [comment]
for what it's worth, here is the content of:
./V3D/Apps/GL/CMakeFiles/slowmoFlowBuilder.dir/link.txt :+1: 
/usr/bin/c++    -Wall -g -g    CMakeFiles/slowmoFlowBuilder.dir/flowBuilder.cpp.
o CMakeFiles/slowmoFlowBuilder.dir/__/__/__/slowmoVideo/lib/flowField_sV.cpp.o C
MakeFiles/slowmoFlowBuilder.dir/__/__/__/slowmoVideo/lib/flowRW_sV.cpp.o  -o slo
wmoFlowBuilder  -L/home/vbr/Documents/slowmoVideo/src/V3D -rdynamic ../../../lib
V3D.a -ljpeg -lpng -lz -lGLU -lGL -lSM -lICE -lX11 -lXext -lGLEW -lglut -Wl,-rpa
th,/home/uid/Documents/slowmoVideo/src/V3D:
and I've check that in any cmakefile I have a reference to X11 in my ubuntu !
my X11 install pkg : 
libx11-6:amd64					install
libx11-data					install
libx11-dev:amd64				install
libx11-doc					install
and my version :+1: Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

hope this can help

**Comment by forresthopkinsa** [comment]
Yeah, there's definitely an X11 reference there. Then again, maybe it's not absolute enough? @pmo-19 said that it needs to have `-I/usr/include/X11` and in the current link file, it looks to only include `-lX11`. I, too, have very limited experience with Cmake development, but could this be related to the problem?

Again, pmo-19, please update us when you compile your commit.

**Comment by pmo-19** [comment]
No I am running Ubuntu 14.04 on a standard PC. In addition I have Windows 8.1 in multi boot.
I have just performed a git clone of slowmovideo. Then at the start of the configuration process it checks for the availability of X11. And it fails to build against X11 shared libraries.

That's it.

I have some trouble pushing the branch I have created. This is my first use of it in GitHub.

`$ git checkout -b x11-in-target-list-libraries
`
`$ ssh -T git@github.com
`
`Hi pmo-19! You've successfully authenticated, but GitHub does not provide shell access.
`
`$ 
`
`$ git push origin x11-in-target-list-libraries
`
`Permission denied (publickey).
`
`fatal: Could not read from remote repository.
`
`Please make sure you have the correct access rights
`
`and the repository exists.
`

I believe that as long as I can connect in ssh I have access right ?
The repository exists as well

`$ git branch -l
`
`  master
`
`* x11-in-target-list-libraries
`
`$ 
`
Do you have any clues for my connection denied ?

**Comment by forresthopkinsa** [comment]
>It fails to build against X11 shared libraries

What? I don't think I understand. Isn't this the original problem? (am I just being dumb?)

**Comment by pmo-19** [comment]
"It fails to build against X11 shared libraries"

Was an answer to @valgit I described the steps on my PC to stumble on the problem of failing to build flowBuilder.cpp.o against X11.

**Comment by pmo-19** [comment]
I successfully connected this time in order to push a new branch for a pull request.

`$ git push origin x11-in-target-list-libraries
`
`ERROR: Permission to slowmoVideo/slowmoVideo.git denied to pmo-19.
`
`fatal: Could not read from remote repository.
`

`Please make sure you have the correct access rights
and the repository exists.
`
`$ 
`

This time it looks like I need to have my account authorized by an admin of the repository ?
I need a write access ...

Can someone help me ?

**Comment by valgit** [comment]
I think you should clone the repository in your own git then create a pull request with your changes

**Comment by pmo-19** [comment]
I have already made a new branch in my own clone repo. as detailed above.

However, AFAIK the create pull request page on this project can only see branches in the GitHub repo. Since my branch is not pushed, I can't create any pull request here.

https://github.com/slowmoVideo/slowmoVideo/compare

That's it. What is your way of living here ? Only you are allowed to create branches and then pull requests on GitHub ? There are other more open projects on GitHub I believe.

**Comment by pmo-19** [comment]
@valgit Just a simple reminder to the owner of this repository:

A basic rule of thumb is that when you have more than 1 user (here you have 3 users on two different platforms) complaining about the very same deficiency, then there is a 100 % chance that your code is deficient.

I have devised a working patch which corrects the afore mentioned deficiencies. However, since the owner of the repo (@valgit) is denying me a write acces to this GitHub repository, therefore preventing me to create a new branch and create right after a pull request, I will keep this to myself only.

If I understand clearly his own postings, everything is right in his published code and complainers are plain idiots.

So long :-)

**Comment by valgit** [comment]
@pmo-19 : I am not the owner, only @Granjow is the real one, he only give me these rights. Now, before having it, I have been able to make pull request from my own clone, so I didn't understand why you can't. Are you sure you have pushed in the good repo ?
Now, if @Granjow is ok with that we can give you direct access.
As for the "everything is right", I would prefer to understand why my code don't compile on other platform before trying to make patches.
If you can make a pull request, why not post your diffs to help ?

**Comment by pmo-19** [comment]
OK. I loosed my nerve in the early process. That was my first pull request on GitHub. I didn't lnow much of all the process. Now the pull request is effective and any one here can review and test it. I believe its modifications are minimal on the original source.

I've seen I don't need a write access to the original repository. So forget about it.

Your point of understanding why you can build (and may be other) is valid. However the most urgent need is to understand why other people cannot build in the first place. in addition, I will need to see your system to fully understand your particular configuration. On some sources, you can build from cmake, from qmake or use command lines instead of Debian helpers ... Building is not a one way street.

I use only standard Debian helpers in fully provisioned debian folders.

**Comment by valgit** [comment]
Hi,

I've merge your pull request, hope this will be for compiling under debian. As for the build process, in my case I only use cmake, now I am more of an OSX and RHEL guy so I only use Ubuntu for basic checking if you can clean the debian process you are welcome.

**Comment by forresthopkinsa** [comment]
Guys, don't merge this yet, ugh. We should test this first.

@pmo-19 you're not supposed to push directly to the master repo. You're supposed to make your own fork/branch/whatever, push to *that*, and once you're debugged and gotten everything working, *then* you submit a PR. On Github. Through the web interface.

It's intentional that write access to the main repo through Git is disabled.

Now, @valgit , before you merge this with the main repo, let's all test @pmo-19 's [branch](https://github.com/pmo-19/slowmoVideo/commits/x11inTargetListLibraries). @lherbolt , you were having the same problem, could you give us a hand and test it too?

Thanks, everybody. I just don't want to be merging changes that haven't been thoroughly tested.

**Comment by valgit** [comment]
Too late but I understand your point ! we can revert if needed but the changes are small. @lherbolt and you @forresthopkinsa  can you retest ? For my part I can only check the OSX build.

**Comment by pmo-19** [comment]
This update of src/CMakeLists.txt should solve debian and RPM builds as well (@lherbolt was using Fedora 22), as long as they use a build process using only cmake without any other command line parameters.

**Comment by forresthopkinsa** [comment]
I can confirm that the latest build is working for me. Thanks!

Although, on a separate note, it seems that SlowmoVideo creates project folders with bad permissions, which makes it so that it can't write the project file. hmmm

**Comment by pmo-19** [comment]
For those on Debian / Ubuntu systems I have a Launchpad repository with up to date Photo (and some Video) Applications for all Ubuntu supported releases:

https://launchpad.net/~anton+/+archive/ubuntu/kde-photo-apps
https://launchpad.net/~anton+/+archive/ubuntu/photo-video-apps

And some various particular or system related applications

https://launchpad.net/~anton+/+archive/ubuntu/miscellaneous

I was trying to build slowmoVideo for the photo-video-apps Launchpad repo.

**Comment by pmo-19** [comment]
@forresthopkinsa Interesting comment about access right of project folders. I didn't test anything yet. Can you details some of the action you made to witness this ?

If you confirm the problem, can you open an issue here ?

**Comment by pmo-19** [comment]
Looking at other issues it looks like the `Gentoo build Failure` issue `#53` arises from the same missing `X11 library` in the set of `target_link_libraries` .

**Comment by forresthopkinsa** [comment]
I'll make a new issue sometime for the permissions error. For now, this is fixed. Thanks everybody for cooperating!

**Comment by lherbolt** [comment]
Hey,
just tested latest git version it on Fedora 22 adn it works.

**Comment by forresthopkinsa** [comment]
Thanks!

**Comment by valgit** [comment]
Hi,
it's OK under OSX, nothing break.

**Comment by forresthopkinsa** [comment]
Cool, the build works then
