### ISSUE TITLE
Request: quick linear graph button

### ISSUE THREAD

**Issue by enetheru** [slowmoVideo/slowmoVideo#48]
My GoPro Hero3+ takes 4k video at 12.5 frames per second. I use slowmovideo to re-time the footage from 12.5fps to 25fps.

To achieve the desired results accurately at the moment I edit the project files to make an exact linear transform. it would be nice to have a button or something to create a linear x=y time graph

I have lots of varying fps footage from my gopro, and use slowmo to retime it all for publishing.

**Comment by Granjow** [comment]
If you right-click in a segment, you should be able to select the speedup factor (0.5 in your case). The start frame has to be placed on a full frame, otherwise every single (not every second) image will be interpolated. There is no feature for this though, but would be useful to move a node to the previous or next full input frame.

**Comment by enetheru** [comment]
excellent, that works. thanks

**Comment by valgit** [comment]
how can we know it's a "flu frame" ?

**Comment by Granjow** [comment]
For the node, both input and output frame has to be an integer value. Then we map the input frame to the output frame exactly.
